### ISSUE TITLE
error 500 when we tried to install it

### ISSUE THREAD

**Issue by mperochon** [typekcz/nocobase-plugins#1]
Hi @typekcz,

Your plugin seems awsome, I tried to install it on the latest version of nocobase, but I get an error 500.

Do i need to make a special thing to install it ?

Thanks for your help :) 

<img width="303" alt="error500" src="https://github.com/user-attachments/assets/a39c3360-f1d0-4305-923b-42737c54aa21">

<img width="431" alt="add_plugin" src="https://github.com/user-attachments/assets/480ac820-3a6a-4769-8d6c-a21035502d6d">

**Comment by typekcz** [comment]
I just tried it on 1.3.18-beta and it installs without problem. Maybe check the log if there is something more specific.
